#!/usr/bin/env python3
"""Send a markdown digest to the configured inbox via Resend.

Called by the competitor-intel skill after it finishes researching.

Usage:
    python send_email.py --subject "Subject" --body-file report.md
    python send_email.py --subject "Subject" --body-file -   # read body from stdin
"""

import argparse
import os
import sys
from datetime import datetime
from pathlib import Path

import markdown
import resend
from dotenv import load_dotenv

EMAIL_FROM = "onboarding@resend.dev"


def load_config() -> tuple[str, str]:
    load_dotenv(Path(__file__).parent / ".env")
    api_key = os.getenv("RESEND_API_KEY")
    email_to = os.getenv("EMAIL_TO")
    missing = [k for k, v in [("RESEND_API_KEY", api_key), ("EMAIL_TO", email_to)] if not v]
    if missing:
        sys.exit(f"ERROR: missing env vars: {', '.join(missing)}. Check your .env file.")
    return api_key, email_to


def render_html(body_md: str) -> str:
    body_html = markdown.markdown(body_md, extensions=["extra", "nl2br", "sane_lists"])
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       max-width: 720px; margin: 0 auto; padding: 24px;
       color: #1a1a1a; line-height: 1.55; }}
h1 {{ font-size: 24px; border-bottom: 2px solid #000; padding-bottom: 8px; }}
h2 {{ font-size: 18px; margin-top: 32px; color: #111; }}
h3 {{ font-size: 15px; margin: 18px 0 6px; color: #333; }}
hr {{ border: none; border-top: 1px solid #e5e5e5; margin: 24px 0; }}
a  {{ color: #0066cc; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
ul {{ padding-left: 20px; }}
li {{ margin-bottom: 6px; }}
code {{ background: #f4f4f4; padding: 1px 5px; border-radius: 3px; font-size: 13px; }}
blockquote {{ border-left: 3px solid #0066cc; padding-left: 14px; color: #555; margin: 12px 0; }}
.footer {{ margin-top: 40px; padding-top: 16px; border-top: 1px solid #eee;
          font-size: 12px; color: #888; }}
</style></head>
<body>
{body_html}
<div class="footer">Generated by competitor-intel skill · {timestamp}</div>
</body>
</html>"""


def read_body(path_arg: str) -> str:
    if path_arg == "-":
        return sys.stdin.read()
    path = Path(path_arg)
    if not path.exists():
        sys.exit(f"ERROR: file not found: {path}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Send digest email via Resend")
    parser.add_argument("--subject", required=True)
    parser.add_argument("--body-file", required=True, help="Markdown file path, or '-' for stdin")
    args = parser.parse_args()

    api_key, email_to = load_config()
    body_md = read_body(args.body_file)
    if not body_md.strip():
        sys.exit("ERROR: empty body, refusing to send.")

    resend.api_key = api_key
    result = resend.Emails.send({
        "from": EMAIL_FROM,
        "to": [email_to],
        "subject": args.subject,
        "html": render_html(body_md),
        "text": body_md,
    })
    print(f"Sent to {email_to} (id: {result.get('id', 'unknown')})")


if __name__ == "__main__":
    main()
